version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres_keycloak
      - KC_DB_DATABASE=keycloak
      - KC_DB_SCHEMA=public

      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=keycloak
    ports:
      - "8080:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak_networks

  postgres_keycloak:
    image: postgres:${POSTGRES_VERSION}
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    volumes:
      - ./data/data_postgres_keycloak:/var/lib/postgresql/data
    networks:
      - keycloak_networks

volumes:
  keycloak:
  data_postgres_keycloak:

networks:
  keycloak_networks:
    driver: bridge
