services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres_keycloak
      - KC_DB_DATABASE=keycloak
      - KC_DB_SCHEMA=public

      - KC_DB_USER=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - sevenhallo

volumes:
  keycloak:

networks:
  sevenhallo:
    driver: bridge
    external: true
