services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=sevenhallo,keycloak
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init/00_create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/00_create-multiple-postgresql-databases.sh
      - ./init/01_create-schemas.sql:/docker-entrypoint-initdb.d/01_create-schemas.sql
      - ./init/02_create-datasourceconfig.sql:/docker-entrypoint-initdb.d/02_create-datasourceconfig.sql
    networks:
      sevenhallo:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local

networks:
  sevenhallo:
    driver: bridge
    external: true
