services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sevenhallo
    ports:
      - "54322:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  sevenhallo:
    driver: bridge
    external: true
