services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
    networks:
      - sevenhallo

  redis_insight:
    image: redislabs/redisinsight:${REDIS_INSIGHT_VERSION}
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - sevenhallo

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  sevenhallo:
    driver: bridge
    external: true
